# Generated by Django 5.2.12 on 2026-03-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
